#!/bin/bash

host=$(ssh rhoban@10.0.0.1 hostname)
robot_home=$(ssh rhoban@10.0.0.1 pwd)
echo "Robot home is "$robot_home

echo "Press enter to init"
read input
rhio 10.0.0.1 init

echo "Press enter to Ned Stark"
read input
rhio 10.0.0.1 /lowlevel/head_pitch/torqueEnable=0

echo "Set by hand the maximum neck angle (the robot must be looking its feet) and press enter..."
read input

IDEAL_PITCH=110.7
value=$(rhio 10.0.0.1 /lowlevel/head_pitch/position)
pitch=$(echo $value| cut -d'=' -f 2)
echo "Pitch is $pitch"
echo "Ideal pitch is $IDEAL_PITCH"
