#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: ./save_monitoring [name]"
else
    if [ -d $1 ]; then
        echo "Directory $1 already exists!"
    else
        mkdir $1
        mv *.jpeg monitoring.log $1/
        cp replay $1/
    fi
fi
