#!/usr/bin/php
<?php

if (count($argv) < 2) {
    die("Usage: ./wifi field [host]\n");
}

// Remote host
$field = $argv[1];
$remote = isset($argv[2]) ? $argv[2] : '10.0.0.1';

if ($remote == '10.0.0.1') {
    $wiface = 'wlp58s0';
}else{
    $wiface = 'wlan0';
}

function cmd($cmd) {
    global $remote;
    $result = trim(`rhio $remote $cmd`);
    return $result;
}

$result = explode('=', cmd('/referee/teamId'));

//Configuration
//$ESSID = 'HL_FIELD_'.$field.'_a';
$ESSID = 'Humanoid-GC'; // Iran
$teamId = $result[1];

//Retrieve robot hostname
$hostname = trim(`ssh rhoban@$remote cat /etc/hostname`);

//Set ip address
$ip = null;


//if ($hostname == 'chewbacca') {
//    $ip = '192.168.'.$teamId.'.105';
//} else if ($hostname == 'nova') {
//    $ip = '192.168.'.$teamId.'.102';
//} else if ($hostname == 'django') {
//    $ip = '192.168.'.$teamId.'.106';
//} else if ($hostname == 'olive') {
//    $ip = '192.168.'.$teamId.'.101';
//} else if ($hostname == 'tom') {
//    $ip = '192.168.'.$teamId.'.104';
//} else if ($hostname == 'arya') {
//    $ip = '192.168.'.$teamId.'.103';
//} else {
//    echo "\e[31mUnknown hostname:\e[m $hostname\n";
//    die;
//}
// Open Iran 2018 configuration
if ($hostname == 'chewbacca') {
    $ip = '192.168.1.45';
} else if ($hostname == 'nova') {
    $ip = '192.168.1.42';
} else if ($hostname == 'django') {
    $ip = '192.168.1.46';
} else if ($hostname == 'olive') {
    $ip = '192.168.1.41';
} else if ($hostname == 'tom') {
    $ip = '192.168.1.44';
} else if ($hostname == 'arya') {
    $ip = '192.168.1.43';
} else {
    echo "\e[31mUnknown hostname:\e[m $hostname\n";
    die;
}

echo "Connecting \e[1m$hostname\e[m to wifi \e[1m$ESSID\e[m with IP \e[1m$ip\e[m (TeamId: \e[1m$teamId\e[m)\n";

//Wifi magic
`ssh rhoban@$remote sudo killall -2 ping 2> /dev/null`;
`ssh rhoban@$remote sudo killall -2 wpa_supplicant 2> /dev/null`;
`ssh rhoban@$remote sudo killall -9 wpa_supplicant 2> /dev/null`;
`ssh rhoban@$remote sudo ifconfig $wiface down`;
`ssh rhoban@$remote sudo ifconfig $wiface up`;
#`ssh rhoban@$remote sudo ifconfig wlan0 down`;
#`ssh rhoban@$remote sudo ifconfig wlan0 up`;
#`ssh rhoban@$remote sudo iwlist wlan0 scan | grep $ESSID`;
#`ssh rhoban@$remote sudo iwconfig wlan0 mode managed essid $ESSID`;

//`ssh rhoban@$remote sudo ifconfig wlan0 $ip netmask 255.255.0.0`;
// Open Iran
`ssh rhoban@$remote sudo ifconfig $wiface $ip netmask 255.255.255.0`;
#`ssh rhoban@$remote sudo ifconfig wlan0 $ip netmask 255.255.255.0`;
//`ssh rhoban@$remote "wpa_passphrase $ESSID humanoidrobot > /tmp/wpa.conf"`;
// OPen IRAN
`ssh rhoban@$remote "wpa_passphrase $ESSID Humanoid2018 > /tmp/wpa.conf"`;
`ssh rhoban@$remote sudo wpa_supplicant -B -i$wiface -c/tmp/wpa.conf -Dwext`;
#`ssh rhoban@$remote sudo wpa_supplicant -B -iwlan0 -c/tmp/wpa.conf -Dwext`;
sleep(3);

//Check to ping to router twice
echo "Check wifi by pinging router:\n";
//$checkPing = `ssh rhoban@$remote ping -W 1 -n -c 2 192.168.0.2`;
// Open d'IRAN : We try to ping the Game Controller
$checkPing = `ssh rhoban@$remote ping -W 1 -n -c 2 192.168.1.2`;

if (strpos($checkPing, '2 received, 0% packet loss')) {
    echo "\e[1mOK. Network is ready.\e[m\n";
} else {
    echo "\e[31mNetwork configuration failed:\e[m\n$checkPing\n";
    die;
}

//Check if RhobanServer listen to the referee
$isServerRunning = `ssh rhoban@$remote ps aux | grep -v "grep" | grep "RhobanServer"`;
if (strpos($isServerRunning, 'RhobanServer')) {
    echo "RhobanServer is running. Check referee state:\n";
    $result = trim(`rhio $remote /referee/state`);
    echo "$result\n";
} else {
    echo "RhobanServer is not running.\n";
    die;
}

