#!/usr/bin/env python3
import sys
import glob
from utils import *

configs = glob.glob("env/wifi_networks/*.yaml")
config_names = [".".join(config.split("/")[-1].split(".")[:-1]) for config in configs]
ip: str = "10.0.0.1" if len(sys.argv) == 1 else sys.argv[1]

if len(sys.argv) < 3:
    while True:
        print("")
        bright("Configuration available: ")
        for config in config_names:
            bright(f"* {config}")

        print("")
        bright("Enter the desired configuration:")
        config: str = input()

        if config in config_names:
            break
else:
    config: str = sys.argv[2]

bright(f"[WIFI] Deploying WiFi configuration {config} to the {ip}")

os.system(f"scp env/wifi_networks/{config}.yaml rhoban@{ip}:/tmp/wifi.yaml")
os.system(f"ssh rhoban@{ip} sudo cp /tmp/wifi.yaml /etc/netplan/00-installer-config-wifi.yaml")
os.system(f"ssh rhoban@{ip} sudo netplan apply")
